make -f Makefiles/clean.gnu clean
make -f Makefiles/make_driverfinal.gnu clean
make -f Makefiles/make_driversample_Test0.gnu clean
make -f Makefiles/make_driversample_Test1.gnu clean
make -f Makefiles/make_driversample_Test2.gnu clean
make -f Makefiles/make_driverbig_10x10_min_output.gnu clean
make -f Makefiles/make_driverbig_10x10_med_output.gnu clean
make -f Makefiles/make_driverbig_10x10_max_output.gnu clean
make -f Makefiles/make_driverbig_30x30_min_output.gnu clean
make -f Makefiles/make_driverbig_30x30_med_output.gnu clean
make -f Makefiles/make_driverbig_30x30_max_output.gnu clean
make -f Makefiles/make_driverbig_8x12_min_output.gnu clean
make -f Makefiles/make_driverbig_8x12_med_output.gnu clean
make -f Makefiles/make_driverbig_8x12_max_output.gnu clean